### ISSUE TITLE
Is 100W realistic with this PCB?

### ISSUE THREAD

**Issue by spooknik** [wagiminator/ATtiny814-USB-PD-Adapter#1]
Hello

Thanks for the projects. I enjoy looking at your work, especially the code. 

It does not seem to me the PCB is set up to support 100W (20V at 5A) The VBUS seems to be all routed through one 0.4mm trace. 

![image](https://user-images.githubusercontent.com/40317809/210958655-d22a9da3-7c83-42cb-9a12-eb3abc3dee97.png)

Running this trace at 5A would result in a 75C over ambient temperature rise if the PCB is 2oz copper. ([Tool](https://www.digikey.dk/en/resources/conversion-calculators/conversion-calculator-pcb-trace-width) used for calculations)

Would it be an improvement to wide this trace to 0.6 mm and bring down the other VBUS from the USB-C? In this way, there is 1.0 - 1.2 mm of combined trace and this should handle 5A at an okay temp even with 1oz of copper.  

![image](https://user-images.githubusercontent.com/40317809/210960529-02e6f08c-5402-4ec8-b56a-5b0b747458ed.png)

**Comment by wagiminator** [comment]
Hi and thank you! The adapter is primarily intended for smaller projects. 5A continuous current are certainly borderline for this small device. In principle, any widening of the tracks in the connector area will certainly help. However, the better solution is probably to remove the solder mask on the power track in this area (but not underneath the connector!) and to reinforce the track with additional solder.

**Comment by spooknik** [comment]
Thanks for the input 👍 

After looking into this a bit, I realize the current shunt resistor should also be changed to something like 5mΩ  and be around 3W in order to handle 5A of current. The 10mΩ current shunt resistor will only read up to 3.2A I believe. 

This line seems to send the config for the INA219 chip: https://github.com/wagiminator/ATtiny814-USB-PD-Adapter/blob/e1635009fa0c9644d1e7a818a29a8e1b2f8267cd/software/USB_PD_Adapter.ino#L141

What I am looking at is adjusting the PGA (Shunt voltage) to be as high as possible. If I understand it correctly, You have set Bits 11 and 12 to both 1 and 1, so the voltage should be 320 mV? I am still learning the ropes of I2C and just wanted to double check I understand correctly.

The [INA219 Datasheet](https://datasheet.lcsc.com/lcsc/1810181516_Texas-Instruments-INA219AIDR_C138706.pdf) for reference. Page 19, Table 4.

**Comment by wagiminator** [comment]
Hi,
10mΩ are fine, the power dissipation at 5A is I²R = (5A)²*0.01Ω = 250mW (the resistor is rated for up to 1W). The shunt voltage at 5A is calculated I*R = 5A*0.01Ω = 50mV. What you have to do IOT measure up to 5A is setting the PGA gain to /2 (bits 12/11 of INA_CONFIG to 0b0010111111111111).

**Comment by spooknik** [comment]
Thanks a lot for the reply, well explained. I was using the wrong formula to calculate power, makes more sense with the right formula 👍

**Comment by spooknik** [comment]
Just to conclude, I modified the PCB as show above and exposed the large positive trace through the shunt resistor. I also added some more vias between ground planes just for extra current capacity. 

Using my thermal camera I measured the hottest point (shunt resistor) on the PCB at around 36C while running at 100W for about 15 minutes. 

Thanks again, it's a handy little tool 🥇
